# Generated by Django 6.0.5 on 2026-06-06 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, help_text='Bitcoin wallet address', max_length=64)),
                ('risk_score', models.FloatField(help_text='Overall wallet risk score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('risk_level', models.CharField(choices=[('LOW', 'Low risk (0-33)'), ('MEDIUM', 'Medium risk (34-66)'), ('HIGH', 'High Risk (67-100)')], help_text='Risk classification', max_length=20)),
                ('total_transaction_analyzed', models.IntegerField(help_text='Number of transactions analyzed')),
                ('high_risk_transaction_count', models.IntegerField(default=0, help_text='Number of transactions flagges as high risk')),
                ('high_risk_transaction_ratio', models.FloatField(default=0.0, help_text='Ratio of high-risk transaction (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('patterns_detected', models.JSONField(default=list, help_text='List of suspicious patterns detected')),
                ('illicit_connection_count', models.IntegerField(default=0, help_text='Number of connections to known illicit addresses.')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='When this analysis was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this analysis was last updated')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about this analysis')),
            ],
            options={
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['wallet_address', '-analyzed_at'], name='wallet_anal_wallet__b92d47_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(db_index=True, help_text='Bitcoin transaction hash', max_length=64)),
                ('tx_timestamp', models.DateTimeField(help_text='When the transaction occurred on blockchain')),
                ('tx_amount_btc', models.DecimalField(decimal_places=8, help_text='Transaction amount in BTC', max_digits=16)),
                ('isolation_forest_score', models.FloatField(help_text='Isolation Forest anomaly score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('local_outlier_factor_score', models.FloatField(help_text='LOF anomaly score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('random_forest_score', models.FloatField(help_text='Random Forest probability of illicit score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ensemble_risk_score', models.FloatField(help_text='Ensemble risk score combining all models (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('risk_level', models.CharField(choices=[('LOW', 'Low risk (0-33)'), ('MEDIUM', 'Medium risk (34-66)'), ('HIGH', 'High Risk (67-100)')], help_text='Risk classification for this transaction', max_length=20)),
                ('is_connected_to_illicit', models.BooleanField(default=False, help_text='Is this transaction connected to known illicit address?')),
                ('connected_illicit_addresses', models.JSONField(default=list, help_text='List of known illicit addresses this tx connects to')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this analysis was created')),
                ('wallet_analysis', models.ForeignKey(help_text='Parent wallet analysis', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet_analyzer.walletanalysis')),
            ],
            options={
                'ordering': ['-ensemble_risk_score'],
                'indexes': [models.Index(fields=['wallet_analysis', '-ensemble_risk_score'], name='wallet_anal_wallet__ca252d_idx'), models.Index(fields=['tx_hash'], name='wallet_anal_tx_hash_7f86cf_idx')],
            },
        ),
    ]
