# Generated by Django 6.0.5 on 2026-06-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_vector', models.JSONField(help_text='Dictionary of {feature_number: value} for all 166 features')),
                ('time_step', models.IntegerField(help_text='Time step in ELliptic daataset(1-49)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_analysis', models.OneToOneField(help_text='Associated transaction analysis', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='wallet_analyzer.transactionanalysis')),
            ],
            options={
                'verbose_name_plural': 'Analysis Features',
            },
        ),
    ]
