# Generated by Django 6.0.5 on 2026-06-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analyzer', '0002_analysisfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletanalysis',
            old_name='total_transaction_analyzed',
            new_name='total_transactions_analyzed',
        ),
    ]
